### PR TITLE
Final Readme

### PR DESCRIPTION
**Pull request by ghost**
With all included, just one commit

### CODE REVIEW

**Comment by Zer0xFF** [comment]
your commit is still not completely accurate, if your PS4 is activate and can open the browser, you can skip the use guide step too, all you need is to start the server, open the browser and type your PC/Laptop IP address.

and as i said, there was no need for a new Pull Request. force updating the old branch would have been fine.

**Comment by ghost** [comment]
Never used pull request on github, so, haven't searched how it does actually work.
I'll look into the User's guide tomorrow, it's late hete in Spain

**Comment by ghost** [comment]
Added IP Adress thing you mentioned
If it's good, let me know

**Comment by Zer0xFF** [comment]
Ya, sounds better, your sentence is accurate but a bit of clarification would be nice, like instead of telling them to skip the fakedns step, give the the actual steps to follow,  can i suggest, the following layout 

> if you have an activated console and have access to the browser, run the server then point your browser to your ip PCs address. 
> 
> If your console has not been activated and as such don't have access to the Web browser, follow these steps... Edit dns, run dns script, run server, open user guide 

And you learned how to force push :) I also didn't get it the 1st time.

**Comment by ghost** [comment]
Done, just splitted the tutorial onto 2 parts and explained how to know which method to use

**Comment by Zer0xFF** [comment]
almost :p
for method 1, you don't need to change the PS4 DNS, its as simple as, python server.py, open the browser and type your IP address.

**Comment by ghost** [comment]
Should be correct now

**Comment by Fire30** [comment]
okay it is merged. Thanks!

**Pull request merged**
